const ACTION_TYPES = {

	//user login action keys 
	USER_NAME_CHANGED: 'USER_NAME',
	PASSWORD_CHANGED: 'PASSWORD_CHANGED',
	SIGNUP_USER_RES: 'SIGNUP_USER_RES',
	FETCHING_DATA: 'FETCHING_DATA',
    RESET_DATA: 'RESET_DATA',
    
    FIRST_NAME_CHANGED:'FIRST_NAME_CHANGED',
    LAST_NAME_CHANGED:'LAST_NAME_CHANGED',
    EMAIL_CHANGED:'EMAIL_CHANGED',
    PASSWORD_CHANGED:'PASSWORD_CHANGED'


	

}

export default ACTION_TYPES
